#!/bin/bash
#
# UFW Blocklist Enhanced Edition - One-Click Installer
# Supports threat intelligence and geographic IP blocking
# Supports Ubuntu and Debian systems

set -e

# Colors for better UI
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
PURPLE='\033[0;35m'
NC='\033[0m' # No Color

# Version information
VERSION="2.0.0"
INSTALL_DATE=$(date +'%Y-%m-%d')

# Paths
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CONFIG_FILE="/etc/default/ufw-blocklist"
UFW_DIR="/etc/ufw"
CRON_DIR="/etc/cron.daily"
MODULE_DIR="/etc/ufw/modules"

# Function to print colored output
print_status() {
    local color="$1"
    local message="$2"
    echo -e "${color}${message}${NC}"
}

# Function to print step header
print_step() {
    local step_num="$1"
    local step_desc="$2"
    print_status "$PURPLE" "
┌─ Step $step_num: $step_desc"
}

# Function to print step completion
print_complete() {
    print_status "$GREEN" "✓ Complete"
}

# Function to print step warning
print_warning() {
    print_status "$YELLOW" "⚠ Warning: $1"
}

# Function to print step error
print_error() {
    print_status "$RED" "✗ Error: $1"
}

# Function to check if running as root
check_root() {
    if [ "$EUID" -ne 0 ]; then
        print_status "$RED" "Error: This installer must be run as root"
        exit 1
    fi
}

# Function to check system requirements
check_requirements() {
    print_step "1" "检查系统要求"

    # Check OS version (Ubuntu/Debian)
    if [ -f /etc/os-release ]; then
        . /etc/os-release
        if [[ "$ID" != "ubuntu" && "$ID" != "debian" ]]; then
            print_error "此安装程序需要 Ubuntu 或 Debian 操作系统"
            exit 1
        fi
        print_status "$BLUE" "  操作系统: $PRETTY_NAME"

        # Set OS-specific information
        case "$ID" in
            ubuntu)
                OS_FAMILY="ubuntu"
                ;;
            debian)
                OS_FAMILY="debian"
                ;;
        esac
    else
        print_error "无法确定操作系统版本"
        exit 1
    fi

    # Check UFW
    if ! command -v ufw >/dev/null 2>&1; then
        print_error "UFW 未安装。请使用: apt install ufw 安装"
        exit 1
    fi
    print_status "$BLUE" "  UFW: $(ufw --version | head -1)"

    # Check ipset
    if ! command -v ipset >/dev/null 2>&1; then
        print_error "ipset 未安装。请使用: apt install ipset 安装"
        exit 1
    fi
    print_status "$BLUE" "  ipset: $(ipset --version | head -1)"

    # Check curl
    if ! command -v curl >/dev/null 2>&1; then
        print_error "curl 未安装。请使用: apt install curl 安装"
        exit 1
    fi
    print_status "$BLUE" "  curl: $(curl --version | head -1)"

    print_complete
    echo
}

# Function to backup existing configuration
backup_existing() {
    print_step "2" "Backing Up Existing Configuration"

    local backup_dir="/etc/ufw-backup-$(date +'%Y%m%d-%H%M%S')"
    mkdir -p "$backup_dir"

    if [ -f "$CONFIG_FILE" ]; then
        cp "$CONFIG_FILE" "$backup_dir/ufw-blocklist.conf.backup"
        print_status "$BLUE" "  Backed up: $CONFIG_FILE"
    fi

    if [ -f "$UFW_DIR/after.init" ]; then
        cp "$UFW_DIR/after.init" "$backup_dir/after.init.backup"
        print_status "$BLUE" "  Backed up: $UFW_DIR/after.init"
    fi

    if [ -f "$CRON_DIR/ufw-blocklist" ]; then
        cp "$CRON_DIR/ufw-blocklist" "$backup_dir/ufw-blocklist.backup"
        print_status "$BLUE" "  Backed up: $CRON_DIR/ufw-blocklist"
    fi

    print_status "$GREEN" "  Backup location: $backup_dir"
    print_complete
    echo
}

# Function to install configuration
install_configuration() {
    print_step "3" "Installing Configuration Files"

    # Create default configuration if not exists
    if [ ! -f "$CONFIG_FILE" ]; then
        print_status "$BLUE" "  Creating default configuration..."
        cat > "$CONFIG_FILE" << 'EOF'
# UFW Blocklist Configuration
# Generated by install.sh on $INSTALL_DATE
# Compatible with Ubuntu and Debian systems

# IP Set Names
THREAT_IPSET="ufw-blocklist-threat"
GEO_IPSET="ufw-blocklist-cn"

# Data Sources
THREAT_URL="https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt"
GEO_URL="http://www.ipdeny.com/ipblocks/data/countries/cn.zone"

# Update Configuration
ENABLE_THREAT_UPDATE="yes"
ENABLE_GEO_UPDATE="no"  # Conservative default

# Update Frequency
THREAT_UPDATE_FREQ="daily"
GEO_UPDATE_FREQ="weekly"

# Default Strategy
DEFAULT_STRATEGY="conservative"

# Logging
LOG_LEVEL="3"
LOG_PREFIX="[UFW BLOCKLIST]"
EOF
        print_status "$GREEN" "  ✓ Default configuration created"
    else
        print_status "$YELLOW" "  ⚠ Configuration file already exists"
        print_status "$BLUE" "    Run 'sudo ufw-blocklist-config --interactive' to reconfigure"
    fi

    chmod 640 "$CONFIG_FILE"
    print_complete
    echo
}

# Function to install scripts
install_scripts() {
    print_step "4" "Installing Enhanced Scripts"

    # Install after.init script
    print_status "$BLUE" "  Installing UFW integration script..."
    cp "$SCRIPT_DIR/after.init" "$UFW_DIR/after.init"
    chmod 750 "$UFW_DIR/after.init"
    print_status "$GREEN" "    ✓ after.init → $UFW_DIR/after.init"

    # Install cron script
    print_status "$BLUE" "  Installing update script..."
    cp "$SCRIPT_DIR/ufw-blocklist" "$CRON_DIR/ufw-blocklist"
    chmod 750 "$CRON_DIR/ufw-blocklist"
    print_status "$GREEN" "    ✓ ufw-blocklist → $CRON_DIR/ufw-blocklist"

    # Install configuration manager
    print_status "$BLUE" "  Installing configuration manager..."
    cp "$SCRIPT_DIR/ufw-blocklist-config" "/usr/local/bin/ufw-blocklist-config"
    chmod 755 "/usr/local/bin/ufw-blocklist-config"
    print_status "$GREEN" "    ✓ ufw-blocklist-config → /usr/local/bin/ufw-blocklist-config"

    # Create module directory
    if [ ! -d "$MODULE_DIR" ]; then
        mkdir -p "$MODULE_DIR"
        print_status "$GREEN" "    ✓ Created module directory: $MODULE_DIR"
    fi

    print_complete
    echo
}

# Function to download initial data
download_initial_data() {
    print_step "5" "Downloading Initial IP Lists"

    . "$CONFIG_FILE"

    # Download threat intelligence
    if [ "$ENABLE_THREAT_UPDATE" = "yes" ]; then
        print_status "$BLUE" "  Downloading threat intelligence list..."
        if curl -sS -f --compressed "$THREAT_URL" -o "/etc/ipsum.3.txt"; then
            local threat_count=$(wc -l < /etc/ipsum.3.txt)
            print_status "$GREEN" "    ✓ Downloaded $threat_count threat IPs"
        else
            print_error "Failed to download threat intelligence from $THREAT_URL"
            exit 1
        fi
        chmod 640 "/etc/ipsum.3.txt"
    else
        print_status "$YELLOW" "  ⚠ Threat intelligence download disabled"
    fi

    # Download geographic data
    if [ "$ENABLE_GEO_UPDATE" = "yes" ]; then
        print_status "$BLUE" "  Downloading geographic IP list..."
        if curl -sS -f "$GEO_URL" -o "/etc/cn.zone"; then
            local geo_count=$(wc -l < /etc/cn.zone)
            print_status "$GREEN" "    ✓ Downloaded $geo_count geographic IP ranges"
        else
            print_error "Failed to download geographic data from $GEO_URL"
            exit 1
        fi
        chmod 640 "/etc/cn.zone"
    else
        print_status "$YELLOW" "  ⚠ Geographic IP download disabled"
    fi

    print_complete
    echo
}

# Function to configure UFW
configure_uw() {
    print_step "6" "Configuring UFW"

    # Check if UFW is active
    if ufw status | grep -q "Status: active"; then
        print_warning "UFW is currently active"
        print_status "$YELLOW" "  This may cause temporary service interruption"

        print_status "$BLUE" "  Continue? (y/N): "
        local proceed
        read -r proceed
        if [[ ! "$proceed" =~ ^[Yy] ]]; then
            print_status "$YELLOW" "Installation cancelled by user"
            exit 0
        fi

        # Create a simple timestamped backup directory
        local backup_dir="/etc/ufw-backup-$(date +'%Y%m%d-%H%M%S')"
        mkdir -p "$backup_dir"

        # Backup current UFW rules and user.rules
        if [ -f "/etc/ufw/user.rules" ]; then
            cp "/etc/ufw/user.rules" "$backup_dir/"
            print_status "$GREEN" "    ✓ Current UFW user rules backed up to $backup_dir"
        fi

        if [ -f "/etc/ufw/after.init" ]; then
            cp "/etc/ufw/after.init" "$backup_dir/"
            print_status "$GREEN" "    ✓ Current after.init backed up to $backup_dir"
        fi

        print_status "$BLUE" "  Note: To restore original rules, run:"
        print_status "$BLUE" "    sudo cp $backup_dir/* /etc/ufw/ && sudo ufw reload"
    else
        print_status "$BLUE" "  UFW is not active - safe to proceed"
    fi

    print_status "$BLUE" "  Applying UFW integration..."
    print_status "$GREEN" "    ✓ UFW integration script installed"

    print_complete
    echo
}

# Function to get user choice
get_user_choice() {
    local prompt="$1"
    local default="$2"
    local choice

    while true; do
        echo -n "$prompt [$default]: "
        read -r choice
        choice="${choice:-$default}"
        case "$choice" in
            [Yy]|[Nn]) break ;;
            *) echo "Please enter Y/y or N/n" ;;
        esac
    done

    echo "$choice"
}

# Function to show final summary
show_summary() {
    . "$CONFIG_FILE"

    print_status "$PURPLE" "
╔════════════════════════════════════════════════════════════════╗
║                    Installation Complete!                             ║
║                                                                      ║
║  UFW Blocklist Enhanced Edition v$VERSION has been installed.          ║
║                                                                      ║
║  Configuration Summary:                                               ║"
    print_status "$BLUE" "║  Threat Intelligence: $([ "$ENABLE_THREAT_UPDATE" = "yes" ] && echo "Enabled" || echo "Disabled")"
    print_status "$BLUE" "║  Geographic Blocking: $([ "$ENABLE_GEO_UPDATE" = "yes" ] && echo "Enabled" || echo "Disabled")"
    print_status "$BLUE" "║  Update Frequencies: Threat=$THREAT_UPDATE_FREQ, Geo=$GEO_UPDATE_FREQ"
    print_status "$BLUE" "║  Default Strategy: $DEFAULT_STRATEGY"
    print_status "$BLUE" "║                                                                      ║
║  Next Steps:                                                         ║
║  1. Test configuration: sudo ufw-blocklist-config --show         ║
║  2. Enable firewall: sudo ufw enable                              ║
║  3. Check status: sudo ufw status                                  ║
║  4. Reconfigure anytime: sudo ufw-blocklist-config --interactive ║
╚════════════════════════════════════════════════════════════════╝"

    if [ "$DEFAULT_STRATEGY" = "conservative" ]; then
        print_status "$YELLOW" "
🔒 Conservative Strategy: Only threat intelligence is enabled."
        print_status "$YELLOW" "   Geographic blocking can be enabled with:"
        print_status "$YELLOW" "   sudo ufw-blocklist-config --interactive"
    fi

    print_status "$GREEN" "
🎉 Installation successful! Your firewall is now enhanced with advanced IP blocking."
}

# Function to show usage
show_usage() {
    echo "UFW Blocklist Enhanced Installer v$VERSION"
    echo "Compatible with Ubuntu and Debian systems"
    echo "Usage: $0 [options]"
    echo
    echo "Options:"
    echo "  -h, --help          Show this help message"
    echo "  -c, --check          Check system requirements only"
    echo "  -b, --backup         Backup existing configuration only"
    echo "  -v, --version        Show version information"
    echo
    echo "Requirements:"
    echo "  - Ubuntu 20.04/22.04/24.04 LTS or Debian"
    echo "  - UFW (Uncomplicated Firewall)"
    echo "  - ipset package"
    echo "  - curl utility"
    echo
    echo "Examples:"
    echo "  $0                  # Full installation"
    echo "  $0 --check          # Check requirements"
    echo "  $0 --backup         # Backup existing setup"
}

# Main execution logic
case "${1:-install}" in
    -h|--help)
        show_usage
        ;;
    -v|--version)
        echo "UFW Blocklist Enhanced Installer v$VERSION"
        echo "Compatible with Ubuntu and Debian systems"
        ;;
    -c|--check)
        check_requirements
        ;;
    -b|--backup)
        backup_existing
        ;;
    install|"")
        check_root
        print_status "$GREEN" "
╔══════════════════════════════════════════════════════════════╗
║              UFW Blocklist Enhanced Installer v$VERSION              ║
║                      Starting Installation...                        ║
╚════════════════════════════════════════════════════════════╝"
        echo
        check_requirements
        backup_existing
        install_configuration
        install_scripts
        download_initial_data
        configure_uw
        show_summary
        ;;
    *)
        print_status "$RED" "Unknown option: $1"
        echo
        show_usage
        exit 1
        ;;
esac