#!/bin/bash
#
# Enhanced ufw-blocklist script supporting multiple IP sources
# Supports both threat IPs and geographic blocking
# Use memory instead of file system to reduce writes to sd card
#
# install this file into /etc/cron.daily/ufw-blocklist-enhanced
#

## Configuration URLs
ipsum_url='https://raw.githubusercontent.com/stamparm/ipsum/master/levels/3.txt'
cn_geo_url='http://www.ipdeny.com/ipblocks/data/countries/cn.zone'

## Configuration
minlen=1000
warn_on_no_change=yes
maxelemheadroom=128

## IP set names - must match ipsets created by after.init
threat_ipsetname="ufw-blocklist-ipsum"
geo_ipsetname="ufw-blocklist-cn"

## Executables
ipset_exe="/usr/sbin/ipset"
logger="/usr/bin/logger -t ufw-blocklist"

## Check if IP sets exist. exit if not - ie no UFW started
check_ipset_exists() {
    local ipsetname="$1"
    "${ipset_exe}" -t list "${ipsetname}" 2>/dev/null
    return $?
}

## Download threat list from IPsum
download_threat_list() {
    $logger "Starting download of threat IPs from ${ipsum_url}"
    local rawlist=$(curl -sS -f --compressed "${ipsum_url}" 2>/dev/null)
    local RET=$?
    if [ $RET -ne 0 ]; then
        $logger "curl error code $RET for ${ipsum_url}"
        return 1
    fi

    # Filter for valid IPv4 addresses only
    echo "${rawlist}" | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}$'
}

## Download geographic list from IPdeny.com
download_geo_list() {
    $logger "Starting download of CN geographic IPs from ${cn_geo_url}"
    local rawlist=$(curl -sS -f "${cn_geo_url}" 2>/dev/null)
    local RET=$?
    if [ $RET -ne 0 ]; then
        $logger "curl error code $RET for ${cn_geo_url}"
        return 1
    fi

    # IPdeny.com already provides clean CIDR format
    echo "${rawlist}"
}

## Update ipset with new list
update_ipset() {
    local ipsetname="$1"
    local newlist="$2"
    local tmpsetname=$(mktemp -u | cut -f2 -d'.')-tmp')

    # Get current count for logging
    if check_ipset_exists "${ipsetname}"; then
        local current_count=$("${ipset_exe}" -t list "${ipsetname}" | grep '^Number of entries:' | cut -d' ' -f4)
        $logger "Updating ${ipsetname} with ${current_count} entries"
    else
        $logger "Creating new ipset ${ipsetname}"
    fi

    # Calculate max elements
    local listlen=$(echo "$newlist" | wc -l)
    local maxelemcount=$(expr $listlen + $maxelemheadroom)

    # Create temporary ipset
    "${ipset_exe}" -q create "${tmpsetname}" hash:net maxelem "${maxelemcount}"
    local RET=$?
    if [ $RET -ne 0 ]; then
        $logger "error code $RET creating temporary ipset ${tmpsetname}"
        "${ipset_exe}" -q destroy "${tmpsetname}"
        return 1
    fi

    # Add entries to temporary ipset
    local cnt=0
    while IFS= read -r ip; do
        # Skip empty lines
        [ -z "$ip" ] && continue

        "${ipset_exe}" add "${tmpsetname}" "$ip"
        cnt=$((cnt + 1))
    done <<< "$newlist"

    # Swap the sets atomically
    "${ipset_exe}" swap "${tmpsetname}" "${ipsetname}"
    RET=$?
    if [ $RET -ne 0 ]; then
        $logger "error code $RET swapping ${tmpsetname} to ${ipsetname}"
        "${ipset_exe}" -q destroy "${tmpsetname}"
        return 1
    fi

    # Clean up
    "${ipset_exe}" -q destroy "${tmpsetname}"
    RET=$?
    if [ $RET -ne 0 ]; then
        $logger "error code $RET destroying temporary ipset ${tmpsetname}"
        return 1
    fi

    $logger "Finished updating ${ipsetname}. New count: ${cnt} of ${listlen}"
    return 0
}

## Main execution logic
main() {
    # Read configuration from /etc/default/ufw-blocklist if exists
    [ -f /etc/default/ufw-blocklist ] && . /etc/default/ufw-blocklist

    # Check what updates are enabled
    local update_threat="yes"
    local update_geo="yes"

    # Check if specific updates are disabled
    [ "$ENABLE_THREAT_UPDATE" = "no" ] && update_threat="no"
    [ "$ENABLE_GEO_UPDATE" = "no" ] && update_geo="no"

    # Update threat IPs
    if [ "$update_threat" = "yes" ]; then
        $logger "Starting threat IP update process"
        local threat_list=$(download_threat_list)
        if [ $? -eq 0 ]; then
            local threat_len=$(echo "$threat_list" | wc -l)
            if [ $threat_len -ge $minlen ]; then
                update_ipset "${threat_ipsetname}" "$threat_list"
            else
                $logger "Threat list has only ${threat_len} IPs. Something must be wrong with ${ipsum_url}"
            fi
        else
            $logger "Failed to download threat list"
        fi
    else
        $logger "Threat IP update is disabled"
    fi

    # Update geographic IPs
    if [ "$update_geo" = "yes" ]; then
        $logger "Starting geographic IP update process"
        local geo_list=$(download_geo_list)
        if [ $? -eq 0 ]; then
            local geo_len=$(echo "$geo_list" | wc -l)
            if [ $geo_len -ge $minlen ]; then
                update_ipset "${geo_ipsetname}" "$geo_list"
            else
                $logger "Geographic list has only ${geo_len} IPs. Something must be wrong with ${cn_geo_url}"
            fi
        else
            $logger "Failed to download geographic list"
        fi
    else
        $logger "Geographic IP update is disabled"
    fi
}

# Execute main function
main "$@"